/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Mriie Stitch Design System — Vibrant
        'surface-dim': '#d9d3cd',
        'on-secondary-fixed-variant': '#0e666a',
        'on-primary-container': '#4d001a',
        'primary-fixed-dim': '#ff5580',
        'secondary-fixed': '#a6eff3',
        'secondary-fixed-dim': '#98e1e5',
        'on-secondary-container': '#005b5f',
        'secondary': '#0e666a',
        'on-primary-fixed': '#000000',
        'surface-bright': '#fbf5f0',
        'on-tertiary-container': '#4a2800',
        'inverse-on-surface': '#a09c98',
        'surface': '#fbf5f0',
        'tertiary': '#874e00',
        'tertiary-dim': '#764400',
        'tertiary-fixed-dim': '#ec8c00',
        'surface-container-highest': '#e2dcd6',
        'outline': '#7a7672',
        'on-tertiary-fixed': '#271300',
        'on-surface': '#302e2b',
        'on-primary': '#ffeff0',
        'surface-tint': '#b70049',
        'inverse-primary': '#ff4e7c',
        'on-background': '#302e2b',
        'primary-container': '#ff7290',
        'surface-container-low': '#f6f0ea',
        'on-secondary-fixed': '#00474a',
        'on-tertiary': '#fff0e5',
        'secondary-container': '#a6eff3',
        'surface-container': '#ede7e2',
        'inverse-surface': '#0f0e0b',
        'tertiary-container': '#ff9800',
        'on-primary-fixed-variant': '#5f0022',
        'surface-variant': '#e2dcd6',
        'tertiary-fixed': '#ff9800',
        'primary-fixed': '#ff7290',
        'outline-variant': '#b1aca8',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#563000',
        'on-surface-variant': '#5e5b57',
        'surface-container-high': '#e7e1dc',
        'primary': '#b70049',
        'on-secondary': '#c8fcff',
        'on-error': '#ffefee',
        'background': '#fbf5f0',
        'error-container': '#fb5151',
        'on-error-container': '#570008',
        'secondary-dim': '#00595d',
        'error-dim': '#9f0519',
        'error': '#b31b25',
        'primary-dim': '#a1003f',
      },
      fontFamily: {
        'headline': ['Newsreader', 'Georgia', 'serif'],
        'body': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      maxWidth: {
        'screen-2xl': '1536px',
      },
    },
  },
  plugins: [],
}
