// AUTO-GENERATED by scripts/sync-payment-links.mjs — do not edit by hand.
// One live Stripe Payment Link per colourway. Re-run the script after any
// price, product or colourway change, then commit the result.

export const paymentLinks = {
  "cover:riviera-stripe": "https://buy.stripe.com/eVq7sK4UU9B38zl50E6Na01",
  "cover:noir-stripe": "https://buy.stripe.com/14A3cu4UU6oR16T8cQ6Na02",
  "cover:signature-mix": "https://buy.stripe.com/7sY6oG2MM00t3f12Sw6Na03",
  "bag:emerald-weave": "https://buy.stripe.com/9B6cN42MM14xaHtgJm6Na04",
  "bag:vintage-plaid": "https://buy.stripe.com/28EfZg4UU4gJ16TgJm6Na05",
  "bag:plaid-forest": "https://buy.stripe.com/dRm28q0EE3cF3f11Os6Na06",
  "bag:pastel-mosaic": "https://buy.stripe.com/7sYdR8bjiaF75n98cQ6Na07",
  "bag:riviera-stripe": "https://buy.stripe.com/3cI3cu5YY28B02P1Os6Na08",
  "bag:cherry-check": "https://buy.stripe.com/6oU8wO3QQ9B3cPBgJm6Na09",
  "bag:charcoal": "https://buy.stripe.com/4gM14m876fZr16T1Os6Na0a",
  "towel:rose-stripe": "https://buy.stripe.com/eVq3cuevu9B316T0Ko6Na0b",
  "towel:bluebell-check": "https://buy.stripe.com/3cI3cucnmcNfcPB50E6Na0c"
}

export const linkFor = (productId, variantId) =>
  paymentLinks[`${productId}:${variantId}`] || null
